### ISSUE TITLE
https://explorer.metacpan.org is not working

### ISSUE THREAD

**Issue by bessarabov** [metacpan/metacpan-explorer#11]
Steps to reproduce:

1. Open https://explorer.metacpan.org
2. Click on `Size of the CPAN` — this actions changes the url to the `https://explorer.metacpan.org/#/5521729`

Result: noting
Expected result: I see the request to metacpan API and its response.

If I open the development console I can see the error: `{message: "Bad credentials", documentation_url: "https://developer.github.com/v3"}`

I tried it in serveral browers with and without privete mode, the result is the same. 

Here is the screenshot:

![screen shot 2016-06-26 at 21 01 23](https://cloud.githubusercontent.com/assets/47263/16363894/78015964-3be1-11e6-936f-8d1aeed8f727.png)

**Comment by rwstauner** [comment]
It should be working now.  Thanks for reporting!
