### ISSUE TITLE
Math::Lapack-0.002

### ISSUE THREAD

**Issue by offtob** [metacpan/metacpan-explorer#21]
Using perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x64-multi-thread (Strawberry perl).
the cpanm -i Math::Lapack-0.002 command fails. The log is attached
[build.log](https://github.com/metacpan/metacpan-explorer/files/11522593/build.log)

**Comment by oalders** [comment]
It looks like this issue should be opened against https://bitbucket.org/ruisteve/math-lapack/src/master/
