### ISSUE TITLE
Graphviz2 fails to install

### ISSUE THREAD

**Issue by offtob** [metacpan/metacpan-explorer#22]
I am using perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x64-multi-thread (Strawberry)
There is NO log file, I have added what I get on screen.

--> Working on Graphviz2
Fetching file://C:\Users\Shahriar\Graphviz2 ... OK
cpanm : 
At line:1 char:1
+ cpanm -i Graphviz2
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
gzip: Graphviz2: unexpected end of file
! Failed to unpack Graphviz2: no directory
! Failed to fetch distribution

**Comment by oalders** [comment]
It looks like this issue should be opened against https://github.com/graphviz-perl/GraphViz2
